#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Created on Feb 26, 2016

@author: Joerg Weingrill <jweingrill@aip.de>

source:
http://infosys.beckhoff.com/index.php?content=../content/1031/tcadsnetref/html/twincat.ads.adserrorcode.html
'''
return_codes = {0x000: 'No Error',
                0x001: 'Internal Error',
                0x002: 'No Rtime',
                0x003: 'Allocation locked memory error.',
                0x004: 'Insert mailbox error.',
                0x005: 'Wrong receive HMSG.',
                0x006: 'Target port not found.',
                0x007: 'Target machine not found.',
                0x008: 'Unknown command ID.',
                0x009: 'Bad task ID.',
                0x00A: 'No IO.',
                0x00B: 'Unknown AMS command.',
                0x00C: 'Win 32 error.',
                0x00D: 'Port is not connected.',
                0x00E: 'Invalid AMS length.',
                0x00F: 'Invalid AMS Net ID.',
                0x010: 'Low Installation level.',
                0x011: 'No debug available.',
                0x012: 'Port disabled.',
                0x013: 'Port is already connected.',
                0x014: 'AMS Sync Win32 error.',
                0x015: 'AMS Sync timeout.',
                0x016: 'AMS Sync AMS error',
                0x017: 'AMS Sync no index map.',
                0x018: 'Invalid AMS port.',
                0x019: 'No memory.',
                0x01A: 'TCP send error.',
                0x01B: 'Host unreachable.',
                0x500: 'Router: no locked memory.',
                0x501: 'Router: mailbox full.',
                0x700: 'error class <device error">',
                0x701: 'Service is not supported by server.',
                0x702: 'Invalid index group.',
                0x703: 'Invalid index offset.',
                0x704: 'Reading/writing not permitted.',
                0x705: 'Parameter size not correct.',
                0x706: 'Invalid parameter value(s).',
                0x707: 'Device is not in a ready state.',
                0x708: 'Device is busy.',
                0x709: 'Invalid context (must be in Windows).',
                0x70a: 'Out of memory.',
                0x70b: 'Invalid parameter value(s).',
                0x70c: '[Device] Not found(files, ...).',
                0x70d: 'Syntax error in command or file.',
                0x70e: 'Objects do not match.',
                0x70f: 'Object already exists.',
                0x710: 'Symbol not found.',
                0x711: 'Symbol version is invalid.',
                0x712: 'Server is not i a valid state.',
                0x713: 'ADS transmode is not supported.',
                0x714: 'Notification handle is invalid.',
                0x715: 'Notification client not registered.',
                0x716: 'No more notification handles.',
                0x717: 'Size for watch to big.',
                0x718: 'Device is not initialized.',
                0x719: 'Device has a timeout.',
                0x71A: 'Query interface has failed.',
                0x71B: 'Wrong interface required.',
                0x71C: 'Class ID is invalid.',
                0x71D: 'Object ID is invalid.',
                0x740: 'Error class <client error>',
                0x741: 'Parameter at service is invalid.', 
                0x742: 'Polling list is empty.',
                0x743: 'Variable connection is already in use.',
                0x744: 'Invoke ID already in use.',
                0x745: 'Timeout has elapsed.',
                0x746: 'Error in win32 subsystem.',
                0x747: 'Timeout value is invalid.',
                0x748: 'Ads port is not opened.',
                0x749: 'No AMS addr.',
                0x750: 'An internal in ADS sync has occured.',
                0x751: 'Hash table overflow.',
                0x752: 'There are no more symbols in the hash table.',
                0x753: 'There are no more symbols in cache.',
                0x754: 'An invalid response has been received.',
                0x755: 'Sync port is locked.'
}
